import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: {
        width: "100%",
        height: "100%",
        justifyContent: "flex-start",
        alignItems: "flex-start",
        backgroundColor: "#f7f7f7",
        paddingLeft: "5%",
        paddingRight: "5%",
    },
    title: {
        width: "50%",
        color: "#000",
        fontSize: 32,
        fontWeight: "700",
        marginTop: "25%",
    },
    subtitle: {
        width: "90%",
        color: "#737a86",
        fontSize: 16,
        fontWeight: "400",
        marginTop: "7%",
    },
    country: {
        width: "100%",
        height: "8%",
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginTop: "10%",
        backgroundColor: "#edeff2",
        borderRadius: 12,
        padding: 15,
    },
    countryInfos: {
        width: "50%",
        height: "100%",
        justifyContent: "center",
        alignItems: "flex-start",
        flexDirection: "column",
        gap: 3,
    },
    countryText: {
        color: "#737a86",
        fontSize: 16,
        fontWeight: "400",
    },
    countryName: {
        color: "#000",
        fontSize: 16,
        fontWeight: "600",
    },
    countryArrow: {
        position: "absolute",
        right: 15,
        width: 24,
        height: 24,
    },
    bottom: {
        width: "100%",
        height: "auto",
        justifyContent: "center",
        alignItems: "center",
        marginTop: "80%",
        gap: 20,
    },
    paragraph: {
        width: "100%",
        color: "#737a86",
        fontSize: 14,
        fontWeight: "400",
        marginTop: "10%",
        textAlign: "center",
    },
    link: {
        color: "#0d6efd",
        fontSize: 14,
        fontWeight: "700",
    },
    button: {
        width: "100%",
        height: 50,
        backgroundColor: "#0d6efd",
        borderRadius: 50,
        justifyContent: "center",
        alignItems: "center",
        marginTop: "10%",
    },
    buttonText: {
        color: "#fff",
        fontSize: 18,
        fontWeight: "700",
    },
});