import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: {
        width: "100%",
        height: "100%",
        justifyContent: "flex-start",
        alignItems: "center",
        backgroundColor: "#f7f7f7",
        paddingLeft: "5%",
        paddingRight: "5%",
    },
    title: {
        width: "90%",
        color: "#000",
        fontSize: 32,
        fontWeight: "700",
        marginTop: "25%",
    },
    image: {
        width: 300,
        height: 300,
        marginTop: "10%",
    },
    instructions: {
        width: "100%",
        height: "auto",
        marginTop: "10%",
        justifyContent: "flex-start",
        alignItems: "flex-start",
        backgroundColor: "#fff",
        borderRadius: 12,
        marginBottom: "10%",
    },
    instruction: {
        width: "100%",
        height: "auto",
        flexDirection: "row",
        justifyContent: "flex-start",
        alignItems: "center",
        gap: 15,
        padding: 15,
    },
    instructionText: {
        width: "80%",
        color: "#000",
        fontSize: 16,
        fontWeight: "600",
    },
    icon: {
        width: 30,
        height: 30,
        justifyContent: "center",
        alignItems: "center",
    },

    loader: {
        position: "absolute",
        bottom: 0,
        width: "120%",
        height: "110%",
        alignItems: "center",
        backgroundColor: "rgba(0,0,0,0.3)",
        borderRadius: 12,
    },
    loaderView: {
        position: "absolute",
        bottom: "4%",
        width: "90%",
        height: "26%",
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: "#fff",
        borderRadius: 12,
        left: "5%",
    },
    loaderWrapper: {
        width: "80%",
        height: "80%",
        justifyContent: "center",
        alignItems: "center",
        gap: 20,
    },
    loaderCircle: {
        width: 100,
        height: 100,
        borderRadius: 100,
        backgroundColor: "#000",
    },
    loaderText: {
        color: "#000",
        fontSize: 24,
        fontWeight: "700",
    },
});