import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: {
        width: "100%",
        height: "100%",
        justifyContent: "flex-start",
        alignItems: "center",
        backgroundColor: "#f7f7f7",
        paddingLeft: "5%",
        paddingRight: "5%",
    },
    title: {
        width: "90%",
        color: "#000",
        fontSize: 32,
        fontWeight: "700",
        marginTop: "25%",
    },
    planInfos: {
        width: "100%",
        marginTop: "10%",
        gap: 20,
        backgroundColor: "#fff",
        borderRadius: 12,
        padding: 20,
    },
    planInfo: {
        width: "100%",
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
    },
    planInfoTitle: {
        color: "#777",
        fontSize: 18,
        fontWeight: "600",
    },
    planInfoInfo: {
        color: "#000",
        fontSize: 15,
        fontWeight: "600",
    },
    addMoneyContainer: {
        width: "100%",
        marginTop: "10%",
        backgroundColor: "#fff",
        borderRadius: 12,
        padding: "5%",
    },
    addMoney: {
        width: "100%",
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
    },
    addMoneyTitle: {
        color: "#777",
        fontSize: 18,
        fontWeight: "500",
    },
    addMoneyInfo: {
        color: "#000",
        fontSize: 15,
        fontWeight: "600",
    },
    addMoneyButtons: {
        width: "100%",
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginTop: 20,
    },
    addMoneyButton: {
        width: "18%",
        height: 40,
        backgroundColor: "#e8f0fc",
        borderRadius: 50,
        justifyContent: "center",
        alignItems: "center",
    },
    addMoneyButtonActive: {
        backgroundColor: "#0d6efd",
    },
    addMoneyButtonText: {
        color: "#0d6efd",
        fontSize: 16,
        fontWeight: "700",
    },
    addMoneyButtonTextActive: {
        color: "#fff",
    },
    amountContainer: {
        width: "100%",
        marginTop: "15%",
        backgroundColor: "#fff",
        borderRadius: 12,
        padding: "5%",
    },
    amount: {
        width: "100%",
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
    },
    amountTitle: {
        color: "#777",
        fontSize: 18,
        fontWeight: "500",
    },
    amountInfo: {
        color: "#000",
        fontSize: 15,
        fontWeight: "400",
    },
    amountCB: {
        width: "100%",
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginTop: 20,
    },
    amountCBIcon: {
        position: "relative",
        width: 50,
        height: 50,
        backgroundColor: "#e8f0fc",
        borderRadius: 50,
        padding: 8,
        justifyContent: "center",
        alignItems: "center",
    },
    amountCBIconLock: {
        position: "absolute",
        bottom: -7,
        right: -7,
        width: 25,
        height: 25,
        backgroundColor: "#fff",
        borderRadius: 50,
        padding: 5,
        justifyContent: "center",
        alignItems: "center",
    },
    amountCBInfo: {
        width: "50%",
        marginLeft: 10,
    },
    amountCBTitle: {
        color: "#777",
        fontSize: 18,
        fontWeight: "500",
    },
    amountCBSubtitle: {
        color: "#000",
        fontSize: 15,
        fontWeight: "400",
    },
    amountCBButton: {
        width: 70,
        height: 30,
        backgroundColor: "#e8f0fc",
        borderRadius: 50,
        justifyContent: "center",
        alignItems: "center",
        marginTop: 5,
    },
    amountCBButtonText: {
        color: "#0d6efd",
        fontSize: 14,
        fontWeight: "700",
    },
    confirmButton: {
        marginTop: "35%",
        width: "100%",
        height: 50,
        backgroundColor: "#0d6efd",
        borderRadius: 50,
        justifyContent: "center",
        alignItems: "center",
    },
    confirmButtonText: {
        color: "#fff",
        fontSize: 16,
        fontWeight: "700",
    },
});